version: 2

updates:
  # Main
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: weekly
      time: "09:00"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 10
    versioning-strategy: increase
    labels: ["dependencies", "language: ruby"]

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      time: "09:00"
      timezone: Asia/Tokyo

  # Docker images
  - package-ecosystem: docker
    directory: "/images/golangci_lint"
    schedule:
      interval: weekly
      time: "09:00"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 10
    labels: ["dependencies", "language: go"]

  - package-ecosystem: docker
    directory: "/images/hadolint"
    schedule:
      interval: weekly
      time: "09:00"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 10
    labels: ["dependencies", "language: misc"]

  - package-ecosystem: docker
    directory: "/images/shellcheck"
    schedule:
      interval: weekly
      time: "09:00"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 10
    labels: ["dependencies", "language: misc"]

  - package-ecosystem: docker
    directory: "/images/actionlint"
    schedule:
      interval: weekly
      time: "09:00"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 10
    labels: ["dependencies", "language: misc"]

  # Java
  - package-ecosystem: gradle
    directory: "/images/checkstyle"
    schedule:
      interval: weekly
      time: "09:00"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 10
    labels: ["dependencies", "language: java"]

  - package-ecosystem: gradle
    directory: "/images/pmd_cpd"
    schedule:
      interval: weekly
      time: "09:00"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 10
    labels: ["dependencies", "language: java"]
    allow:
      - dependency-name: "*pmd-dist*"

  - package-ecosystem: gradle
    directory: "/images/pmd_java"
    schedule:
      interval: weekly
      time: "09:00"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 10
    labels: ["dependencies", "language: java"]

  # Java (Kotlin)
  - package-ecosystem: gradle
    directory: "/images/detekt"
    schedule:
      interval: weekly
      time: "09:00"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 10
    labels: ["dependencies", "language: kotlin"]

  - package-ecosystem: gradle
    directory: "/images/ktlint"
    schedule:
      interval: weekly
      time: "09:00"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 10
    labels: ["dependencies", "language: kotlin"]

  # JavaScript
  - package-ecosystem: npm
    directory: "/images/eslint"
    schedule:
      interval: weekly
      time: "09:00"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 10
    versioning-strategy: increase
    labels: ["dependencies", "language: javascript"]

  - package-ecosystem: npm
    directory: "/images/jshint"
    schedule:
      interval: weekly
      time: "09:00"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 10
    versioning-strategy: increase
    labels: ["dependencies", "language: javascript"]

  - package-ecosystem: npm
    directory: "/images/coffeelint"
    schedule:
      interval: weekly
      time: "09:00"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 10
    versioning-strategy: increase
    labels: ["dependencies", "language: javascript"]

  - package-ecosystem: npm
    directory: "/images/remark_lint"
    schedule:
      interval: weekly
      time: "09:00"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 10
    versioning-strategy: increase
    labels: ["dependencies", "language: markdown"]

  - package-ecosystem: npm
    directory: "/images/stylelint"
    schedule:
      interval: weekly
      time: "09:00"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 10
    versioning-strategy: increase
    labels: ["dependencies", "language: css"]

  - package-ecosystem: npm
    directory: "/images/tyscan"
    schedule:
      interval: weekly
      time: "09:00"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 10
    versioning-strategy: increase
    labels: ["dependencies", "language: typescript"]

  # PHP
  - package-ecosystem: composer
    directory: "/images/code_sniffer"
    schedule:
      interval: weekly
      time: "09:00"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 10
    versioning-strategy: increase
    labels: ["dependencies", "language: php"]
    ignore:
      - dependency-name: "cakephp/cakephp-codesniffer" # We cannot support CakePHP 4.x still. See #748

  - package-ecosystem: composer
    directory: "/images/phinder"
    schedule:
      interval: weekly
      time: "09:00"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 10
    versioning-strategy: increase
    labels: ["dependencies", "language: php"]

  - package-ecosystem: composer
    directory: "/images/phpmd"
    schedule:
      interval: weekly
      time: "09:00"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 10
    versioning-strategy: increase
    labels: ["dependencies", "language: php"]

  # Python
  - package-ecosystem: pip
    directory: "/images/cpplint"
    schedule:
      interval: weekly
      time: "09:00"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 10
    labels: ["dependencies", "language: c/c++"]

  - package-ecosystem: pip
    directory: "/images/metrics_complexity"
    schedule:
      interval: weekly
      time: "09:00"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 10
    labels: ["dependencies", "language: misc"]

  - package-ecosystem: pip
    directory: "/images/flake8"
    schedule:
      interval: weekly
      time: "09:00"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 10
    labels: ["dependencies", "language: python"]

  - package-ecosystem: pip
    directory: "/images/pylint"
    schedule:
      interval: weekly
      time: "09:00"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 10
    labels: ["dependencies", "language: python"]

  - package-ecosystem: pip
    directory: "/images/actionlint"
    schedule:
      interval: weekly
      time: "09:00"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 10
    labels: ["dependencies", "language: misc"]

  # Ruby
  - package-ecosystem: bundler
    directory: "/images/brakeman"
    schedule:
      interval: weekly
      time: "09:00"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 10
    versioning-strategy: increase
    labels: ["dependencies", "language: ruby"]

  - package-ecosystem: bundler
    directory: "/images/goodcheck"
    schedule:
      interval: weekly
      time: "09:00"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 10
    versioning-strategy: increase
    labels: ["dependencies", "language: misc"]

  - package-ecosystem: bundler
    directory: "/images/haml_lint"
    schedule:
      interval: weekly
      time: "09:00"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 10
    versioning-strategy: increase
    labels: ["dependencies", "language: ruby"]

  - package-ecosystem: bundler
    directory: "/images/querly"
    schedule:
      interval: weekly
      time: "09:00"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 10
    versioning-strategy: increase
    labels: ["dependencies", "language: ruby"]

  - package-ecosystem: bundler
    directory: "/images/reek"
    schedule:
      interval: weekly
      time: "09:00"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 10
    versioning-strategy: increase
    labels: ["dependencies", "language: ruby"]

  - package-ecosystem: bundler
    directory: "/images/rubocop"
    schedule:
      interval: weekly
      time: "09:00"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 10
    versioning-strategy: increase
    labels: ["dependencies", "language: ruby"]

  - package-ecosystem: bundler
    directory: "/images/scss_lint"
    schedule:
      interval: weekly
      time: "09:00"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 10
    versioning-strategy: increase
    labels: ["dependencies", "language: css"]

  - package-ecosystem: bundler
    directory: "/images/slim_lint"
    schedule:
      interval: weekly
      time: "09:00"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 10
    versioning-strategy: increase
    labels: ["dependencies", "language: ruby"]

  - package-ecosystem: bundler
    directory: "/images/secret_scan"
    schedule:
      interval: weekly
      time: "09:00"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 10
    versioning-strategy: increase
    labels: ["dependencies", "language: ruby"]
